name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 🧱 Compiling Martins LDP Python Scripts
      run: |
        sudo apt-get update
        sudo apt-get -y install texlive-font-utils linuxdoc-tools-text linuxdoc-tools-latex docbook-dsssl docbook-xsl docbook-utils htmldoc htmldoc-common docbook-xsl html2text docbook5-xml docbook-xsl-ns jing asciidoc libxml2-utils python3-stdeb fakeroot python3-all python3-networkx python3-nose fop ldp-docbook-xsl ldp-docbook-dsssl docbook opensp dh-python
        cd
        git clone https://github.com/tLDP/python-tldp
        cd python-tldp && rm -rf debian
        python3 setup.py --command-packages=stdeb.command bdist_deb
        sudo dpkg -i deb_dist/python3-tldp_*_all.deb
        cd
        ldptool --dump-cfg
# happy end.
